# Generated by Django 5.0 on 2024-03-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_link_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='user_id',
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signup.customuser'),
            preserve_default=False,
        ),
    ]
