# Generated by Django 5.0 on 2024-03-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_remove_link_user_id_link_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='user',
            new_name='user_id',
        ),
    ]
